# Hey, thanks for using my theme. If you like this theme,checkout my repo (https://gitlab.com/avron/gruvhugo"
# and drop a star while you're at it. ;)
# baseurl = "https://avron.gitlab.io/gruvhugo/"
# baseURL = "https://example.org/"
baseURL = "https://jimmy97332.github.io/"
title = "Tsai-Ting Chen"
languageCode = "en-us"
paginate = "10" # Number of posts per page
#disqusShortname = "" # Enable comments by entering your Disqus shortname
#googleAnalytics = "" # Enable Google Analytics by entering your tracking id
#-------------------------------------------------------------------------------
# DEFAULT SETTINGS
#-------------------------------------------------------------------------------

# Default Theme
theme= "gruvhugo"

# Default Post Extension
defaultExtension= "html"

# Default metadata format for newly created frontmatter using
# hugo new command. "toml", "yaml", or "json"
metaDataFormat= "yaml"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params.main]
  enabled = true
  lang = "en"
  enableKatex = true
  metaKeywords = "fast, hugo, theme, minimal, gruvbox"
  name = "tsai_ting_chen"
  headerTitle = "Tsai-Ting Chen"
  copyright = "© 2024 Tsai-Ting Chen."
  keywords = "Gruvhugo, Hugo, Theme, Blog, Personal Website, Community page, free software, fediverse"
  img = "img/author.jpg"
  # Thanks to Christina @ wocintechchat.com for this photo.
  icon = "img/logo.png"
  quote = "Board Man Gets Paid."
  description= """
  <p>
  My name is Tsai-Ting Chen. 
  I am currently a junior backend software engineer working in the comprehensive automated logistics industry based in Taiwan, 
  providing solutions for global consumer brands and retailers across various channels and strategies.
  <br/>
  I learned programming through self-study and government training programs, 
  successfully transitioning from a financial analyst position.
  My key skills are in Java and the Spring framework for 
  developing web application services and maintaining microservice-based automation systems on Linux servers.
  <br/>
  I am a proactive learner who is always eager to explore and adopt new technologies. 
  I believe in the value of hard work and consistently strive to improve my skills and contribute to my team's success. 
  This website is not actively updated. If you find my qualifications fit your needs, 
  please feel free to contact me at <a href="mailto:jimmy97332@gmail.com">jimmy97332@gmail.com</a>.
  </i>
  """
  licenseUrl = "https://gitlab.com/avron/gruvhugo/-/raw/master/LICENSE.md"

[params.style]
  # add path to custom CSS files here
  custom_css = ["css/style.css"]

 # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:jimmy97332@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/tsai-ting-jimmy-chen-49836b159/"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"

  [[menu.main]]
    identifier = "CV"
    name       = "Curriculum Vitae"
    url        = "cv/"

  [[menu.main]]
    identifier = "publications"
    name       = "Publications"
    url        = "none"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.asciidocExt]
    backend = "html5"
    docType = "article"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = true
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
